
#
default: &default
  adapter: postgresql
  encoding: unicode


  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Twittercloneapp_development




test:
  <<: *default
  database: Twittercloneapp_test


production:
  <<: *default
  database: Twittercloneapp_production
  username: Twittercloneapp
  password: <%= ENV['TWITTERCLONEAPP_DATABASE_PASSWORD'] %>
